parameters:
  wordpress.driver.blackbox.class: WordHat\Extension\Driver\BlackboxDriver

services:
  wordpress.driver.blackbox:
    class: "%wordpress.driver.blackbox.class%"
    tags:
      - { name: wordpress.driver, alias: blackbox }
