parameters:
  wordpress.driver.wpcli.class: WordHat\Extension\Driver\WpcliDriver
  wordpress.element.wpcli.cache.class: WordHat\Extension\Driver\Element\Wpcli\CacheElement
  wordpress.element.wpcli.comment.class: WordHat\Extension\Driver\Element\Wpcli\CommentElement
  wordpress.element.wpcli.content.class: WordHat\Extension\Driver\Element\Wpcli\ContentElement
  wordpress.element.wpcli.database.class: WordHat\Extension\Driver\Element\Wpcli\DatabaseElement
  wordpress.element.wpcli.plugin.class: WordHat\Extension\Driver\Element\Wpcli\PluginElement
  wordpress.element.wpcli.term.class: WordHat\Extension\Driver\Element\Wpcli\TermElement
  wordpress.element.wpcli.theme.class: WordHat\Extension\Driver\Element\Wpcli\ThemeElement
  wordpress.element.wpcli.user.class: WordHat\Extension\Driver\Element\Wpcli\UserElement
  wordpress.element.wpcli.widget.class: WordHat\Extension\Driver\Element\Wpcli\WidgetElement

services:
  wordpress.driver.wpcli:
    class: "%wordpress.driver.wpcli.class%"
    arguments:
      - "%wordpress.driver.wpcli.alias%"
      - "%mink.base_url%"
      - "%wordpress.driver.wpcli.binary%"
      - "%wordpress.path%"
    tags:
      - { name: wordpress.driver, alias: wpcli }

  wordpress.element.wpcli.cache:
    class: "%wordpress.element.wpcli.cache.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: cache, driver: wpcli }

  wordpress.element.wpcli.comment:
    class: "%wordpress.element.wpcli.comment.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: comment, driver: wpcli }

  wordpress.element.wpcli.content:
    class: "%wordpress.element.wpcli.content.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: content, driver: wpcli }

  wordpress.element.wpcli.database:
    class: "%wordpress.element.wpcli.database.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: database, driver: wpcli }

  wordpress.element.wpcli.plugin:
    class: "%wordpress.element.wpcli.plugin.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: plugin, driver: wpcli }

  wordpress.element.wpcli.term:
    class: "%wordpress.element.wpcli.term.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: term, driver: wpcli }

  wordpress.element.wpcli.theme:
    class: "%wordpress.element.wpcli.theme.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: theme, driver: wpcli }

  wordpress.element.wpcli.user:
    class: "%wordpress.element.wpcli.user.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: user, driver: wpcli }

  wordpress.element.wpcli.widget:
    class: "%wordpress.element.wpcli.widget.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: widget, driver: wpcli }
