parameters:
  # Parameters.
  wordpress.parameters: {}

services:
  wordpress.wordpress:
    class: 'WordHat\Extension\WordpressDriverManager'
    arguments:
      - {}
  wordpress.context.initializer:
    class: 'WordHat\Extension\Context\Initialiser\WordpressAwareInitialiser'
    arguments:
      - "@wordpress.wordpress"
      - "%wordpress.parameters%"
    tags:
      - { name: context.initializer }
  wordpress.listener.driver:
    class: 'WordHat\Extension\Listener\DriverListener'
    arguments:
      - "@wordpress.wordpress"
      - "%wordpress.parameters%"
    tags:
      - { name: event_dispatcher.subscriber, priority: 0 }
